-- GAG2 Config (загружается через GAG2 Loader, автообновление каждые 2 мин)
getgenv().GAG2 = {
    Fps = 5,
    MergeEclipseMoon = true,
    MailDelay = 150,
    World = "FallHarvest", -- or Main
    MovementMethod = "Tween", -- или "Teleport"
    AutoBuySeed = true,
    BuyGearShop = {
        "Super Syrup Watering Can","Super Syrup Sprinkler",
    },
    BuyGearMinSheckles = 500000,
    PlantSeeds = {
        ["Maple Carrot"] = 10,
        ["Maple Strawberry"] = 10,
        ["Maple Blueberry"] = 10,
        ["Maple Tulip"] = 10,
        ["Maple Tomato"] = 10,
        ["Maple Apple"] = 10,
        ["Maple Corn"] = 10,
        ["Maple Cactus"] = 10,
        ["Maple Pineapple"] = 10,
        ["Maple Mushroom"] = 10,
        ["Maple Green Bean"] = 10,
        ["Maple Banana"] = 10,
        ["Maple Grape"] = 10,
        ["Maple Coconut"] = 10,
        ["Maple Mango"] = 10,
        ["Maple Dragon Fruit"] = 10,
        ["Maple Acorn"] = 10,
        ["Maple Cherry"] = 10,
        ["Maple Sunflower"] = 10,
        ["Atlantic Giant Pumpkin"] = 10,
        ["Maple Venus Fly Trap"] = 10,
        ["Maple Pomegranate"] = 10,
        ["Maple Poison Apple"] = 10,
        ["Maple Venom Spitter"] = 10,
        ["Conifer Cone"] = 10,
        ["Amber Cranberry"] = 10,
        ["Gold"] = 10,
        ["Rainbow"] = 10,
        ["Mega"] = 10,
    },
    SeedInventoryLimit = {
        ["Maple Carrot"] = 10,
        ["Maple Strawberry"] = 10,
        ["Maple Blueberry"] = 10,
        ["Maple Tulip"] = 10,
        ["Maple Tomato"] = 10,
        ["Maple Apple"] = 10,
        ["Maple Corn"] = 10,
        ["Maple Cactus"] = 10,
        ["Maple Pineapple"] = 10,
        ["Maple Mushroom"] = 10,
        ["Maple Green Bean"] = 10,
        ["Maple Banana"] = 10,
        ["Maple Grape"] = 10,
        ["Maple Coconut"] = 10,
        ["Maple Mango"] = 10,
        ["Maple Dragon Fruit"] = 10,
        ["Maple Acorn"] = 10,
        ["Maple Cherry"] = 10,
        ["Maple Sunflower"] = 10,
        ["Atlantic Giant Pumpkin"] = 10,
        ["Maple Venus Fly Trap"] = 10,
        ["Maple Pomegranate"] = 10,
        ["Maple Poison Apple"] = 10,
        ["Maple Venom Spitter"] = 10,
        ["Conifer Cone"] = 10,
        ["Amber Cranberry"] = 10,
    },
    ["seed dont buy"] = {
        "Moon Bloom",
        "Hypno Bloom","Dragon's Breath",
    },
    BuyPets = {
        ["Frog"] = { Big = 99, Huge = 99, Rainbow = 99 },
        ["Bunny"] = { Big = 99, Huge = 99, Rainbow = 99 },
        ["Owl"] = { Big = 99, Huge = 99, Rainbow = 99 },
        ["Deer"] = { Normal = 6, Big = 99, Huge = 99, Rainbow = 99 },
        ["Turtle"] = { Big = 99, Huge = 99, Rainbow = 99 },
        ["Robin"] = { Big = 99, Huge = 99, Rainbow = 99 },
        ["Bee"] = { Big = 99, Huge = 99, Rainbow = 99 },
        ["Butterfly"] = { Big = 99, Huge = 99, Rainbow = 99 },
        ["Monkey"] = { Big = 99, Huge = 99, Rainbow = 99 },
        ["Golden Dragonfly"] = { Normal = 6, Big = 99, Huge = 99, Rainbow = 99 },
        ["Bear"] = { Big = 99, Huge = 99, Rainbow = 99 },
        ["Bald Eagle"] = { Big = 99, Huge = 99, Rainbow = 99 },
        ["Firefly"] = { Big = 99, Huge = 99, Rainbow = 99 },
        ["Unicorn"] = 6,
        ["Raccoon"] = math.huge,
    },
    EquipPets = {
        ["Unicorn"] = {Priority = 1},
        ["Golden Dragonfly"] = {Priority = 2},
        ["Deer"] = {Priority = 3},
    },
    SellPets = {
    },
    UseGear = {
        "Common Watering Can",
        "Common Sprinkler", "Uncommon Sprinkler", "Rare Sprinkler","Legendary Sprinkler",
    },
    CollectSeedPacks = true,
    COLLECT_PLANT_IF_MUTATED = {"Mushroom","Rocket Pop","Pomegranate","Venom Spitter","Venus Fly Trap",
    "Dragon's Breath","Hypno Bloom","Moon Bloom","Poison Apple","Sunflower","Fire Fern","Sun Bloom","Star Fruit"
    },
    SellFruitMultiplier = {
        ["Pomegranate"] = 2, ["Venom Spitter"] = 2, ["Venus Fly Trap"] = 2, ["Dragon's Breath"] = 2, ["Hypno Bloom"] = 2, ["Moon Bloom"] = 2, ["Rocket Pop"] = 2, ["Mushroom"] = 2,
        ["Poison Apple"] = 2, ["Sunflower"] = 2, ["Fire Fern"] = 2,
    },
    BuyAuction = {
        ["Common Egg"] = 5000000,
        ["Sun Bloom"] = 150000000,
        ["Star Fruit"] = 500000000,
    },
    GearInventoryLimit = {
        ["Common Sprinkler"] = 20,
        ["Uncommon Sprinkler"] = 20,
        ["Common Watering Can"] = 20,
        ["Rare Sprinkler"] = 20,
        ["Legendary Sprinkler"] = 20,
    },
    BuyCrateShop = {
        -- "Light Crate", "Arch Crate",
    },
    CrateInventoryLimit = {
        -- ["Light Crate"] = 5,
    },
    OpenSeedPacks = {
        --"Common Seed Pack", "Uncommon Seed Pack", "Rare Seed Pack",
    },
    OpenEggs = {
        "Common Egg",
    },
    LimitPlants = 500,
    ExpandLimit = 4,
    MaxPetSlots = 6,
    MailReceivers = {""},
    MailSendItems = {
        ["Raccoon"] = 1,---{ Amount = 1, To = {"account"} },
        ["Moon Bloom"] = "All",
        ["Dragon's Breath"] = "All",
        ["Super Sprinkler"] = "All",
        ["Super Watering Can"] = "All",
        ["Mega"] = "All",
        ["Sun Bloom"] = "All",
        ["Star Fruit"] = "All",
    },

    ShowUserWebhook = true,
    WebhookUrl = "",
    DiscordId = "",
    RamKickLimit = 7000,
}
