-- GAG2 Public Config
getgenv().GAG2 = {
    Fps = 13,
    AutoBuySeed = true,
    BuyGearShop = {
        "Common Sprinkler", "Uncommon Sprinkler","Common Watering Can", "Rare Sprinkler","Super Sprinkler","Super Watering Can",
    },
    BuyGearMinSheckles = 500000,
    PlantSeeds = {
        ["Strawberry"] = 1, ["Blueberry"] = 1,
        ["Tomato"] = 1, ["Apple"] = 10, ["Corn"] = 1,
        ["Cactus"] = 1, ["Pineapple"] = 30, ["Green Bean"] = 1,
        ["Banana"] = 20, ["Grape"] = 40, ["Coconut"] = 40, ["Mango"] = 70,["Rocket Pop"] = 200, ["Bamboo"] = 350,
        ["Dragon Fruit"] = 70, ["Acorn"] = 70, ["Cherry"] = 70, ["Sunflower"] = 10, ["Fire Fern"] = 10, ["Mushroom"] = 200,
    },
    DestroyPlants = {
        "Carrot", "Strawberry", "Blueberry", "Tulip", "Tomato", "Apple","Corn",
        "Cactus", "Green Bean", "Banana",
    },
    BuyPets = {
        ["Monkey"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Golden Dragonfly"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Deer"] = {Normal = 4, Big = 99, Huge = 99, Rainbow = 99},
        ["Bear"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Bald Eagle"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Butterfly"] = math.huge,
        ["Frog"] = {Huge = 99, Rainbow = 99},
        ["Turtle"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Rabbit"] = { Huge = 99},
        ["Firefly"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Unicorn"] = {Big = 99, Huge = 99, Rainbow = 99},
        ["Raccoon"] = math.huge,
    },
    EquipPets = {
        ["Unicorn"] = {Priority = 1},
        ["Deer"] = {Priority = 2},
    },
    SellPets = {},
    UseWateringCans = {"Common Watering Can"},
    UseSprinklers = {
     "Uncommon Sprinkler"
    },
    CollectSeedPacks = true,
    COLLECT_PLANT_IF_MUTATED = {"Sunflower", "Venus Fly Trap", "Fire Fern", "Mushroom", "Rocket Pop","Bamboo","Pomegranate","Poison Apple","Acorn","Coconut","Dragon Fruit","Mango","Banana","Grape", "Pineapple"},
    SellFruitMultiplier = {
        ["Mushroom"] = 2,
        ["Rocket Pop"] = 2,
        ["Bamboo"] = 0.83,
        ["Sunflower"] = 3,
        ["Venus Fly Trap"] = 3,
        ["Fire Fern"] = 3,
        ["Pomegranate"] = 3,
        ["Poison Apple"] = 3,
        ["Acorn"] = 0.83,
        ["Coconut"] = 0.83,
        ["Dragon Fruit"] = 0.83,
        ["Banana"] = 0.83,
        ["Grape"] = 0.83,
        ["Pineapple"] = 0.83,
    },
    BuyAuction = {
        ["Common Seed Pack"] = 25000,
        ["Uncommon Seed Pack"] = 150000,
        ["Rare Seed Pack"] = 1000000,
        ["Legendary Seed Pack"] = 10000000,
        ["Ghost Pepper Pack"] = 10000000,
        ["Common Egg"] = 6000000,
        ["Moon Bloom"] = 8000000,
        ["Sun Bloom"] = 200000000,
        ["Hypno Bloom"] = 10000000,
        ["Dragon's Breath"] = 10000000,
        ["Star Fruit"] = 400000000,
        ["Super Watering Can"] = 2000000,
        ["Super Sprinkler"] = 1000000,
    },
    ["seed dont buy"] = {
        "Venus Fly Trap","Pomegranate","Poison Apple","Venom Spitter","Moon Bloom","Hypno Bloom","Fire Fern","Sunflower","Dragon's Breath","Acorn","Cherry","Coconut",
    },
    SeedInventoryLimit = {
        ["Cactus"] = 10,["Green Bean"] = 1,["Banana"] = 1,["Grape"] = 1,["Coconut"] = 1,["Mango"] = 1,
        ["Dragon Fruit"] = 1,["Acorn"] = 1,["Cherry"] = 1,["Sunflower"] = 1,["Fire Fern"] = 999,
    },
    GearInventoryLimit = {},
    BuyCrateShop = {},
    CrateInventoryLimit = {},
    OpenSeedPacks = {},
    OpenEggs = {},
    DestroyUntilMinPlants = 300,
    LimitPlants = 300,
    PlantOverLimit = {"Bamboo","Mushroom","Rocket Pop",},
    ExpandLimit = 3,
    MaxPetSlots = 6,
    MailReceivers = {"Prdeparitozo"},
    MailSendItems = {
        ["Carrot"] = { Amount = "3000", To = {"Unitopikazf"} },
        ["Trowel"] = { Amount = "500", To = {"Unitopikazf"} },
        ["Raccoon"] = 1,
        ["Firefly"] = 1,
        ["Moon Bloom"] = "All",
         ["Sun Bloom"] = "All",
         ["Star Fruit"] = "All",
        ["Dragon's Breath"] = "All",
        ["Rainbow"] = "3",
        ["Common Egg"] = { Amount = "All", To = {"AFK_MVP"} },
        ["Super Watering Can"] = { Amount = "All", To = {"Unitopikazf"} },
        ["Super Sprinkler"] = { Amount = "All", To = {"Unitopikazf"} },
        ["Mega"] = "3",
        ["Hypno Bloom"] = "All",
        ["Monkey"] = "All",
        ["Golden Dragonfly"] = "All",
        ["Deer"] = "All",
        ["Bald Eagle"] = "All",
        ["Butterfly"] = "All",
        ["Frog"] = "All",
        ["Bear"] = "All",
        ["Unicorn"] = "All",
        ["Turtle"] = "All",
        
    },
    ShowUserWebhook = true,
    WebhookUrl = "https://discord.com/api/webhooks/1521560645529764013/AL7LzY7ZEXnFDNFpyCAkRQ2vtfZrLebLJEVg2fzoKB4Of6kM1ejanGwelFu8HOZVu2Xj",
    DiscordId = "",
    ServerSpread = false,
    UUID = "",
    RamKickLimit = 6000,
}
